### ISSUE TITLE
user instructions for Butler?

### ISSUE THREAD

**Issue by Heiko910** [cassidyjames/butler#50] opened 2024-11-07 21:04 UTC
Hi there,
I just installed Butler for the first time. I played around with it for a while and then I was trying to add my Home Assistant account to it, so I changed from the demo server to home-assistant.io. Now I am stuck on the Dashboard showing the Home Assistant Homepage in full screen and I can't get back into the butler settings to change the server address. 
Is there a keyboard short cut to exit full screen or to enter the settings menu?

Is there a good source for instructions for Butler ? 

Thanks

**Comment by Heiko910** [comment] 2024-11-07 21:13
Sorry guys for wasting our time. 
I figured it out, with Ctrl-Alt-Shift-F I was able to get out of the full screen mode and then I remembered that my server for HA isn't the HA webpage but my self-hosted HA server. IP address plus Port and it works. 

The issue was in between my two ears ;-)

**Comment by cassidyjames** [comment] 2024-11-12 18:17
I think the core issue here will be resolved with #25; I mention how to get out of it briefly since #6 but I agree that it's not enough.

I'll go ahead and close this as effectively a duplicate of #25. :)

**Closed** 2024-11-12 18:18 UTC
