### ISSUE TITLE
Can't enter Username or Password on mobile

### ISSUE THREAD

**Issue by hotswapster** [cassidyjames/butler#49] opened 2024-09-30 04:32 UTC
I installed Butler version 1.3.0 in FuriOS from Gnome Software.

At the log in screen, I can't enter any text. The cursor appears in the username and password fields but no letters appear when typing.

**Comment by cassidyjames** [comment] 2024-10-02 17:38
Thanks for reporting this! Unfortunately I believe it's a duplicate of #27. I've not been able to track down the issue so far, but I will spend some time playing on my GNOME phone to see what the issue could be.

**Closed** 2024-10-02 17:39 UTC
